In [1]:
import numpy as np
import pandas as pd

import folium
import webbrowser

In [2]:
local_data = pd.DataFrame(columns=["SGG행정구역별","행정구역별", "물류이동개수"])
local_data["SGG행정구역별"] = pd.Series([11,21,22,23,24,25,26,29,31,32,33,34,35,36,37,38,39])
local_data["행정구역별"] = pd.Series(["서울특별시","부산광역시","대구광역시","인천광역시",
                                         "광주광역시","대전광역시","울산광역시","세종특별자치시",
                                    "경기도","강원도", "충청북도","충청남도","전라북도",
                                    "전라남도","경상북도","경상남도","제주특별자치도"])

local_count={"서울특별시":0,"부산광역시":0,"대구광역시":0,"인천광역시":0,
             "광주광역시":0,"대전광역시":0,"울산광역시":0,"세종특별자치시":0,
             "경기도":0,"강원도":0, "충청북도":0,"충청남도":0,"전라북도":0,
             "전라남도":0,"경상북도":0,"경상남도":0,"제주특별자치도":0}

local_count["서울특별시"]+=1
local_count["경기도"]+=1
local_count["서울특별시"]+=1
local_count["경기도"]+=1
local_count["서울특별시"]+=1

local_count["서울특별시"]+=1
local_count["충청북도"]+=1
local_count["서울특별시"]+=1
local_count["충청남도"]+=1
local_count["서울특별시"]+=1

local_data.index = local_data["행정구역별"]
local_data["물류이동개수"] = pd.Series(local_count)


local_data.to_csv("local_data.csv",index=False, encoding = 'euc-kr')
local_data

         SGG행정구역별    행정구역별  물류이동개수
행정구역별
서울특별시          11    서울특별시       6
부산광역시          21    부산광역시       0
대구광역시          22    대구광역시       0
인천광역시          23    인천광역시       0
광주광역시          24    광주광역시       0
대전광역시          25    대전광역시       0
울산광역시          26    울산광역시       0
세종특별자치시        29  세종특별자치시       0
경기도            31      경기도       2
강원도            32      강원도       0
충청북도           33     충청북도       1
충청남도           34     충청남도       1
전라북도           35     전라북도       0
전라남도           36     전라남도       0
경상북도           37     경상북도       0
경상남도           38     경상남도       0
제주특별자치도        39  제주특별자치도       0

In [3]:
def main():
    
    

    #csvFile = 'Si_Do_Parcel_Distribution.csv'
    csvFile = "local_data.csv"
    SiDodf = pd.read_csv(csvFile, encoding = 'euc-kr')
    print(SiDodf)
    
    SiDo_geo = 'Si_Do_map_utf8.json'
    
    # Initialize the map at Daejeon 
    m = folium.Map(location=[36.45, 127.42], \
                   tiles="OpenStreetMap", zoom_start=8)
    
# Json map polygon 경계좌표값으로 구역별 색칠하기 
    folium.Choropleth(
        geo_data = SiDo_geo,
        name='권역별 택배 물류 이동 비율',
        data=SiDodf,
        columns=['행정구역별', '물류이동개수'],
        key_on='feature.properties.CTP_KOR_NM',
        fill_color='PuRd',
        fill_opacity=0.7,
        line_opacity=0.2,
        legend_name='권역별 택배 물류 이동 비율').add_to(m)

    # 색칠한 layer 켜고 끄기 버튼 추가
    folium.LayerControl().add_to(m)
    
    m.save('map.html')
    webbrowser.open('map.html') 
    
    folium.LayerControl().add_to(m)
    
    m.save('map.html')
    webbrowser.open('map.html') 
    



# main 함수 로딩부
if __name__ == '__main__':
    main()

    SGG행정구역별    행정구역별  물류이동개수
0         11    서울특별시       6
1         21    부산광역시       0
2         22    대구광역시       0
3         23    인천광역시       0
4         24    광주광역시       0
5         25    대전광역시       0
6         26    울산광역시       0
7         29  세종특별자치시       0
8         31      경기도       2
9         32      강원도       0
10        33     충청북도       1
11        34     충청남도       1
12        35     전라북도       0
13        36     전라남도       0
14        37     경상북도       0
15        38     경상남도       0
16        39  제주특별자치도       0